apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp
resources:
  - ../../base/

replicas:
  - name: myapp
    count: 2
images:
  - name: nginx
    newTag: 1.25.3-alpine3.18

commonLabels:
  owner: dev
    