apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp
resources:
  - ../../base/

replicas:
  - name: myapp
    count: 1
images:
  - name: nginx
    newTag: 1.25.3-alpine3.18

metadata:
  name: myapp
  labels:
    environment: dev