apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp
resources:
  - ../../base/
  - hpa.yaml  

replicas:
  - name: myapp
    count: 2
images:
  - name: nginx
    newTag: stable-alpine3.17
namePrefix: dev-

