apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp
resources:
  - ../../base/
  - hpa.yaml

replicas:
  - name: myapp
    count: 4
images:
  - name: nginx
    newTag: 1.25.3-alpine3.18



