apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp
resources:
  - ../../base/

replicas:
  - name: myapp
    count: 3

metadata:
  name: myapp
  labels:
    environment: stage    
    
