apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: monitoring-git-repo  # Change the name to something unique
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/fluxcd/flux2-monitoring-example.git
