---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dashboard
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./monitoring/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring-git-repo 
    namespace: myapp
  targetNamespace: flux-system
